services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn rag_chatbot.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: ENV
        value: prod
      - key: DJANGO_SETTINGS_MODULE
        value: rag_chatbot.settings
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: rag_chatbot

databases:
  - name: mongodb
    databaseName: rag_chatbot
    plan: free
      