services:
  - type: web
    name: django-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rag_chatbot.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        value: ""
